version: "3.4"
services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/config/.env
    expose:
      - 8080
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - media:/app/media
      - static:/app/static
    depends_on:
      - postgres
    networks:
      - internal
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/config/.env
    networks:
      - internal
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/dist:ro
      - media:/media:ro
      - static:/static:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail-shrimp.middlewares=to-https@file"
      - "traefik.http.routers.mail-shrimp.rule=Host(`api.mail.mintyhint.com`) || Host(`mail.mintyhint.com`) || Host(`www.mail.mintyhint.com`)"
      - "traefik.http.routers.mail-shrimp.entrypoints=web"
      - "traefik.http.routers.mail-shrimp-secure.rule=Host(`api.mail.mintyhint.com`) || Host(`mail.mintyhint.com`) || Host(`www.mail.mintyhint.com`)"
      - "traefik.http.routers.mail-shrimp-secure.middlewares="
      - "traefik.http.routers.mail-shrimp-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mail-shrimp-secure.tls=true"
      - "traefik.http.routers.mail-shrimp-secure.entrypoints=web-secure"
    networks:
      - internal
      - traefikproxy
volumes:
  static:
  media:
  postgres_data:


networks:
  internal:
  traefikproxy:
    name: traefikproxy
    external: true