# Generated by Django 5.0.4 on 2024-05-03 10:20

import django.db.models.deletion
import mail_accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField()),
                ('dkim_selector', models.CharField()),
                ('dkim_key_size', models.IntegerField()),
                ('dkim', models.CharField()),
                ('dkim_public', models.CharField()),
                ('dkim_dns_zone_file', models.CharField()),
                ('dkim_private', models.CharField()),
                ('quota', mail_accounts.models.PosIntegerOrInfinityField()),
                ('max_mailbox_quota', mail_accounts.models.PosIntegerOrInfinityField()),
                ('max_mailboxes', mail_accounts.models.PosIntegerOrInfinityField()),
                ('max_aliases', mail_accounts.models.PosIntegerOrInfinityField()),
            ],
        ),
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField()),
                ('username', models.CharField()),
                ('password', models.CharField(max_length=128)),
                ('quota', mail_accounts.models.PosIntegerOrInfinityField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_boxes', to='mail_accounts.domain')),
            ],
        ),
    ]
