# Generated by Django 5.0.4 on 2024-05-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_accounts', '0002_alter_domain_domain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='domain_name',
            new_name='name',
        ),
    ]
